FLASK_APP=microblog.py
SQLALCHEMY_DATABASE_URI=app.db
FLASK_ENV=development
FLASK_DEBUG=1

SECRET_KEY=supersecretpassword


DB_USERNAME=''
DB_PASSWORD=''
DB_HOST=''
DB_DB_NAME=''

MAIL_SERVER=localhost
MAIL_PORT='8025'

MS_TRANSLATOR_KEY=''